### ISSUE TITLE
Crash using latest version

### ISSUE THREAD

**Issue by Royal-Jelly** [shift02/LittleServantMod#7]
Saber profession crashes on attack in freedom mode.
<details><summary>CLICK ME</summary>
<p>

```
Time: 3/11/19 6:57 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.item.ItemStack.func_77972_a(ItemStack.java:347)
	at net.minecraft.item.ItemSword.func_77644_a(ItemSword.java:54)
	at net.minecraft.item.ItemStack.func_77961_a(ItemStack.java:366)
	at littleservantmod.entity.EntityLittleServantFakePlayer.attackTargetEntityWithCurrentItem(EntityLittleServantFakePlayer.java:386)
	at littleservantmod.entity.EntityLittleServantFakePlayer.func_70652_k(EntityLittleServantFakePlayer.java:235)
	at littleservantmod.entity.ai.EntityAIAttackMelee2.checkAndPerformAttack(EntityAIAttackMelee2.java:172)
	at littleservantmod.entity.ai.EntityAIAttackMelee2.func_75246_d(EntityAIAttackMelee2.java:162)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at littleservantmod.entity.EntityLittleServantBase.func_70636_d(EntityLittleServantBase.java:268)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at littleservantmod.entity.EntityLittleServantFakePlayer.func_70071_h_(EntityLittleServantFakePlayer.java:94)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.item.ItemStack.func_77972_a(ItemStack.java:347)
	at net.minecraft.item.ItemSword.func_77644_a(ItemSword.java:54)
	at net.minecraft.item.ItemStack.func_77961_a(ItemStack.java:366)
	at littleservantmod.entity.EntityLittleServantFakePlayer.attackTargetEntityWithCurrentItem(EntityLittleServantFakePlayer.java:386)
	at littleservantmod.entity.EntityLittleServantFakePlayer.func_70652_k(EntityLittleServantFakePlayer.java:235)
	at littleservantmod.entity.ai.EntityAIAttackMelee2.checkAndPerformAttack(EntityAIAttackMelee2.java:172)
	at littleservantmod.entity.ai.EntityAIAttackMelee2.func_75246_d(EntityAIAttackMelee2.java:162)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at littleservantmod.entity.EntityLittleServantBase.func_70636_d(EntityLittleServantBase.java:268)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at littleservantmod.entity.EntityLittleServantFakePlayer.func_70071_h_(EntityLittleServantFakePlayer.java:94)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: littleservantmod:little_servant (littleservantmod.entity.EntityLittleServant)
	Entity ID: 5387
	Entity Name: Little Servant
	Entity's Exact location: 160.25, 70.00, 262.65
	Entity's Block location: World: (160,70,262), Chunk: (at 0,4,6 in 10,16; contains blocks 160,0,256 to 175,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['King_Royal_Jelly'/1037, l='New World', x=163.12, y=70.00, z=262.00]]
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 4982018355797391102
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (172,64,256), Chunk: (at 12,4,0 in 10,16; contains blocks 160,0,256 to 175,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3887 game time, 3887 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 28666 (now: false), thunder time: 45393 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.15.0-39-generic
	Java Version: 1.8.0_191, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 911184432 bytes (868 MB) / 1735393280 bytes (1655 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2815 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID               | Version      | Source                                  | Signature                                |
	|:------ |:---------------- |:------------ |:--------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft        | 1.12.2       | minecraft.jar                           | None                                     |
	| LCHIJA | mcp              | 9.42         | minecraft.jar                           | None                                     |
	| LCHIJA | FML              | 8.0.99.99    | forge-1.12.2-14.23.5.2815-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge            | 14.23.5.2815 | forge-1.12.2-14.23.5.2815-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | littleservantmod | 0.0.11       | LittleServantMod[v0.0.11].jar           | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['King_Royal_Jelly'/1037, l='New World', x=163.12, y=70.00, z=262.00]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
[06:57:08] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# /home/jelly/.local/share/multimc/instances/Little Servant mod [1.12.2]/.minecraft/crash-reports/crash-2019-03-11_06.57.08-server.txt
[06:57:08] [Client thread/INFO] [FML]: Waiting for the server to terminate/save.
[06:57:08] [Server thread/INFO] [FML]: Unloading dimension 0
[06:57:08] [Server thread/INFO] [FML]: Applying holder lookups
[06:57:08] [Server thread/INFO] [FML]: Holder lookups applied
[06:57:08] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[06:57:08] [Client thread/INFO] [FML]: Server terminated.
[06:57:08] [Client Shutdown Thread/INFO] [minecraft/MinecraftServer]: Stopping server
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code 255.```

</p>
</details>

**Comment by shift02** [comment]
Thanks for the report!

I will check it
